
services:
  nextjs:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app   # Monta el código fuente en el contenedor para reflejar cambios
      - /app/node_modules  # Asegura que `node_modules` no se sobrescriba
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - NODE_ENV=development  # Configura el entorno de desarrollo
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
